input_channels: 3  # RGB satellite imagery
multi_scale_channels: 64
residual_channels: 64
num_classes: 2  # Assuming binary classification (slum / non-slum)

transformer:
  dim: 64
  depth: 6
  heads: 8
  mlp_dim: 128
  dropout: 0.1

fpn_channels: [64, 32, 16, 8]  # Channels for each FPN layer
channel_attention_reduction_ratio: 16
spactial_attention_kernel_size: 7
decoder_channels: [8, 16, 32]  # Channels for each decoder layer
